apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.namespace.app | default .Release.Name }}
    app.kubernetes.io/managed-by: "Helm"