apiVersion: apps/v1
kind: Deployment
metadata:
  name: grayscaler
  namespace: it6-ns
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: grayscaler
  template:
    metadata:
      labels:
        app: grayscaler
    spec:
      containers:
      - name: grayscaler
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8000