apiVersion: v1
kind: Service
metadata:
  name: grayscaler-service
  namespace: it6-ns
spec:
  type: {{ .Values.service.type }}
  selector:
    app: grayscaler
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8000  # port exposed inside your container
