apiVersion: v1
kind: Service
metadata:
  name: grascaler-service
  namespace: it6-ns
spec:
  type: {{ .Values.service.type }}
  selector:
    app: grascaler
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8000
    nodePort: 30021
