replicaCount: 1

image:
  repository: docker.io/library/grayscaler
  tag: offline
  pullPolicy: Never

service:
  type: ClusterIP
  port: 8012

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

namespace:
  name: it6-ns
  app: grayscaler
